-- SQL: 数据库表单初始化脚本

-- 1. Stations 表 (站点元数据)
CREATE TABLE public.stations (
    -- Primary Key
    hash_id text PRIMARY KEY,
    
    -- Metadata fields
    provider text NOT NULL,
    name text NOT NULL,
    campus_id integer,
    campus_name text,
    lat double precision,
    lon double precision,
    
    -- Data type for list of device IDs (jsonb is often preferred in PG)
    device_ids jsonb, 
    
    -- Timestamps
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz NOT NULL -- 遵循 Fetcher 提供的元数据时间
);

-- 索引：提高按 provider 查询的速度
CREATE INDEX stations_provider_idx ON public.stations (provider);


-- 2. Usage 表 (历史使用记录)
CREATE TABLE public.usage (
    -- Primary Key (Auto-incrementing)
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Foreign Key to stations
    hash_id text NOT NULL REFERENCES public.stations(hash_id) ON DELETE CASCADE,
    
    -- Usage Data
    snapshot_time timestamptz NOT NULL,
    free integer NOT NULL DEFAULT 0,
    used integer NOT NULL DEFAULT 0,
    total integer NOT NULL DEFAULT 0,
    error integer NOT NULL DEFAULT 0,
    
    -- 复合索引：提高历史查询效率
    UNIQUE (hash_id, snapshot_time)
);


-- 3. Latest 表 (最新状态缓存)
CREATE TABLE public.latest (
    -- Primary Key (也是 Foreign Key)
    hash_id text PRIMARY KEY REFERENCES public.stations(hash_id) ON DELETE CASCADE,
    
    -- Usage Data (与 usage 表结构一致)
    snapshot_time timestamptz NOT NULL,
    free integer NOT NULL DEFAULT 0,
    used integer NOT NULL DEFAULT 0,
    total integer NOT NULL DEFAULT 0,
    error integer NOT NULL DEFAULT 0
);